"""agregar is_open y open_category a combo_items

Revision ID: 0dea99306ec4
Revises: 0001
Create Date: 2026-03-28 23:41:27.532299

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificadores de revisión usados por Alembic
revision: str = '0dea99306ec4'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('combo_items', sa.Column('is_open', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('combo_items', sa.Column('open_category', sa.String(length=50), nullable=True))
    op.alter_column('combo_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('combo_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('combo_items', 'open_category')
    op.drop_column('combo_items', 'is_open')
    # ### end Alembic commands ###
