"""agregar wpp_token a whatsapp_numbers

Revision ID: 676b100f5333
Revises: b504cb07262e
Create Date: 2026-03-31 20:18:16.185830

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificadores de revisión usados por Alembic
revision: str = '676b100f5333'
down_revision: Union[str, None] = 'b504cb07262e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_numbers', sa.Column('wpp_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_numbers', 'wpp_token')
    # ### end Alembic commands ###
